/*
 * API Wars
 *
 * API Wars is supposed to be a benchmarking test for API frameworks and the APIs will have to be written in compliance with this API specification. 
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Helloworld struct {

	Message string `json:"Message,omitempty"`
}
